# 开发环境配置
server:
  # 服务器的HTTP端口，默认为9999
  port: 9999
  servlet:
    context-path: /api

spring:
  config:
    #这里里面放着一些私密的不能开源的配置
    import: "optional:application-sec.yml"
  profiles:
    active: dev
  application:
    name: Code-Nest
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
  # Spring Security 全局配置
  security:
    user:
      # 完全禁用默认用户
      name: 
      password: 
      roles:

# JWT配置
jwt:
  # JWT密钥（HS512算法要求至少64字节）
  secret: A0I5+vaOwhnQpPdtIxs0H+lKBa+tU6c8aP+Ppj5msSco0GSvcEo21JYJlAztsFPGiQ/jHRcXzS+asTbcj2LqFA==
  # 访问令牌过期时间（秒）2小时
  expiration: 7200
  # 刷新令牌过期时间（秒）7天
  refresh-expiration: 604800
  # 签发者
  issuer: code-nest

# MyBatis配置
mybatis:
  # 映射文件位置
  mapper-locations: classpath*:mapper/**/*.xml
  # 实体类别名包路径（支持所有模块的domain包）
  type-aliases-package: com.xiaou.*.domain
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 开启二级缓存
    cache-enabled: true
    # 延迟加载
    lazy-loading-enabled: true

# 日志配置（使用logback-spring.xml配置文件）
logging:
  config: classpath:logback-spring.xml
  level:
    # 禁用 Spring Security 的默认日志
    org.springframework.boot.autoconfigure.security: OFF
    org.springframework.security: WARN

# SpringDoc OpenAPI 3.0 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  group-configs:
    - group: 'default'
      display-name: 'Code-Nest API'
      paths-to-match: '/**'