CREATE TABLE IF NOT EXISTS `sys_agent_audit` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '审计ID',
  `audit_id` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '智能体审计业务ID',
  `confirmation_id` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '前端确认ID',
  `idempotency_key` varchar(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '写入动作幂等键',
  `user_message` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '管理员自然语言指令',
  `intent` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '智能体意图',
  `action_id` varchar(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '动作目录ID',
  `route` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '关联管理端路由',
  `risk_level` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '动作目录风险等级',
  `risk_category` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '智能体风险分类',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PREVIEW' COMMENT '状态：PREVIEW/CONFIRMED/CANCELLED/EXECUTED/FAILED',
  `summary` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '智能体摘要',
  `payload_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '预览参数JSON',
  `diff_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '字段差异JSON',
  `plan_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '执行计划JSON',
  `result_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '执行结果JSON',
  `error_message` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '执行失败或取消原因',
  `operator_id` bigint NULL DEFAULT NULL COMMENT '操作管理员ID',
  `operator_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '操作管理员名称',
  `confirmed_time` datetime NULL DEFAULT NULL COMMENT '确认时间',
  `executed_time` datetime NULL DEFAULT NULL COMMENT '执行完成时间',
  `created_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_agent_audit_id` (`audit_id` ASC) USING BTREE,
  UNIQUE INDEX `uk_agent_idempotency_key` (`idempotency_key` ASC) USING BTREE,
  INDEX `idx_agent_confirmation_id` (`confirmation_id` ASC) USING BTREE,
  INDEX `idx_agent_intent` (`intent` ASC) USING BTREE,
  INDEX `idx_agent_action_id` (`action_id` ASC) USING BTREE,
  INDEX `idx_agent_status` (`status` ASC) USING BTREE,
  INDEX `idx_agent_risk_category` (`risk_category` ASC) USING BTREE,
  INDEX `idx_agent_operator_id` (`operator_id` ASC) USING BTREE,
  INDEX `idx_agent_created_time` (`created_time` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '管理员智能体审计表' ROW_FORMAT = Dynamic;
